package util

const ApiPattern = "/api"
const RootPattern = "/"
const V1 = "/v1"
const UsersPattern = "/users"
const ContextKey = "userId"
const UrlKeyId = "id"
const UrlKeyLastId = "lastId"
const UrlKeyFav = "fav_id"
const UrlKeyConn = "conn_id"
const UrlKeyPreference = "preference_id"
const UrlKeyConnReqId = "conn_req_id"
const RowsAffected = "rowsAffected"
const LastId = "lastId"
const BucketName = "com.biyelap.main"
const BucketRegion = "us-geo"
const BucketNameTest = "com.biyelap.test"
const InternalServerError = "Internal Server Error"
const NotFound = "not found"
const Error = "error"
